[package]
name = "email-server-core"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
derive_builder = "0.20.2"
tokio = { version = "1.43.0", features = ["full"] }
bytes = "1.10.0"
async-trait = "0.1.86"
