[package]
name = "email-server"
edition = "2021"
version.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.31", features = ["derive", "env"] }
email-server-core = { path = "../email-server-core" }
tokio = { version = "1.43.0", features = ["full"] }
